INSERT INTO skill(`name`) VALUES('Java');
INSERT INTO skill(`name`) VALUES('MySQL');
INSERT INTO skill(`name`) VALUES('C#');
INSERT INTO skill(`name`) VALUES('C++');
INSERT INTO skill(`name`) VALUES('Python');
INSERT INTO skill(`name`) VALUES('Ruby');
INSERT INTO skill(`name`) VALUES('HTML');
INSERT INTO skill(`name`) VALUES('CSS');
INSERT INTO skill(`name`) VALUES('PHP');
INSERT INTO skill(`name`) VALUES('JavaScript');

INSERT INTO resource(`name`) VALUES('Ernest Hemingway');
INSERT INTO resource(`name`) VALUES('Leo Tolstoy');
INSERT INTO resource(`name`) VALUES('Jane Austen');
INSERT INTO resource(`name`) VALUES('Charles Dickens');
INSERT INTO resource(`name`) VALUES('William Shakespeare');
INSERT INTO resource(`name`) VALUES('F. Scott Fitzgerald');
INSERT INTO resource(`name`) VALUES('Stephen King');
INSERT INTO resource(`name`) VALUES('Mark Twain');
INSERT INTO resource(`name`) VALUES('William Faulkner');
INSERT INTO resource(`name`) VALUES('Virginia Woolf');
INSERT INTO resource(`name`) VALUES('James Joyce');
INSERT INTO resource(`name`) VALUES('Vladamir Nabokov');
INSERT INTO resource(`name`) VALUES('George Orwell');
INSERT INTO resource(`name`) VALUES('J. R. R Tolkien');
INSERT INTO resource(`name`) VALUES('Fyodor Dostoyevsky');
INSERT INTO resource(`name`) VALUES('J. D. Salinger');
INSERT INTO resource(`name`) VALUES('Franz Kafka');
INSERT INTO resource(`name`) VALUES('C. S. Lewis');
INSERT INTO resource(`name`) VALUES('Toni Morrison');
INSERT INTO resource(`name`) VALUES('J. K. Rowling');
INSERT INTO resource(`name`) VALUES('Herman Melville');
INSERT INTO resource(`name`) VALUES('John Steinbeck');

INSERT INTO project(`name`) VALUES('Manhattan Project');
INSERT INTO project(`name`) VALUES('Operation Anthropoid');
INSERT INTO project(`name`) VALUES('Project Newcastle');
INSERT INTO project(`name`) VALUES('Bon Echo');
INSERT INTO project(`name`) VALUES('Incident of 57th Street');
INSERT INTO project(`name`) VALUES('Revolution');
